import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { AppstoreOutlined } from "@ant-design/icons";
import { CalculatorOutlined } from "@ant-design/icons";
import { UserOutlined } from "@ant-design/icons";
import { ShareAltOutlined } from "@ant-design/icons";


export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen bg-[#171821] w-screen">
          <div className="grid grid-cols-4 gap-1">
            <div className="bg-[#171821]  text-justify col-span-1 border-r border-white/30">
              <Image
                className=" lg:1 md:1 sm:block mt-10 ml-10"
                src="/asset/profile.png"
                width={150}
                height={100}
                alt="profile"
              />
              <div className="flex justify-center text-justify p-2 text-lg ">
                <ul>
                  <Link href="/dashboard">
                  
                    <li className=" flex items-center justify-center gap-3  boarder rounded font-bold mb-5 text-white text-center w-52 h-10
                    // ${selectedMenuItem === 'dashboard' ? 'bg-blue-500' : ''}`}
                    // onClick={() => setSelectedMenuItem('dashboard')}
                  ">
                    <AppstoreOutlined />
                      Dashboard
                    </li>
                  </Link>
                  <Link href="/account">
                  <li className=" flex items-center justify-center gap-3  boarder rounded font-bold mb-5 text-white text-center w-52 h-10">
                  <UserOutlined />
                    Account
                  </li>
                  </Link>
                  <Link href="/calculator">
                  <li className=" flex items-center justify-center gap-3  boarder rounded font-bold mb-5 text-white text-center w-52 h-10">
                  <CalculatorOutlined />
                    Calculator
                  </li>
                  </Link>
                  <Link href="/refferal">
                  <li className=" flex items-center justify-center gap-3  boarder rounded font-bold mb-5 text-white text-center w-52 h-10">
                  <ShareAltOutlined />
                    Refferal
                  </li>
                  </Link>
                </ul>
              </div>
            </div>


          
            

            {/* <div className={`${isClicked === true ? "bg-pink" : "bg-transparent"}`}>

            </div> */}

            <div className="col-span-3 w-full">
              <div className="bg-[#21222d] boarder rounded mt-7 mb-5 text-white text-end h-20 mr-5">
                <button className="bg-blue-500/80 boarder rounded mt-5 mb-5 text-white text-center h-8 mr-4  w-20  ">
                  Connect
                </button>
              </div>

              <div className="bg-[#171821] h-screen">{children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
