"use client"


import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { AppstoreOutlined } from "@ant-design/icons";
import { CalculatorOutlined } from "@ant-design/icons";
import { UserOutlined } from "@ant-design/icons";
import { ShareAltOutlined } from "@ant-design/icons";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import { usePathname } from "next/navigation";

const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  const pathname = usePathname()
  
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-[#171821]">
          <div className="grid grid-cols-5 gap-1">
            <div className=" text-justify hidden lg:block lg:col-span-1 border-r border-white/30">
              <Image
                className=" lg:1 md:1 sm:block mt-10 ml-10"
                src="/asset/profile.png"
                width={150}
                height={100}
                alt="profile"
              />
              <div className="flex justify-center text-justify p-2 text-lg mt-8 ">
                <ul>
                  <Link href="/dashboard">
                    <li
                     
                      className={`flex items-center justify-center gap-3 border rounded border-none font-bold mb-5 text-white text-center h-10}`}
                    >
                      <Button className="w-full h-12 bg-[#171821]" variant={pathname == "/dashboard" ? 'outline' : "ghost"}>
                        <AppstoreOutlined className="mr-2 h-4" />
                        Dashboard
                      </Button>
                    </li>
                  </Link>
                  <Link href="/account">
                    <li
                      className={`flex items-center justify-center gap-3 border rounded border-none font-bold mb-5 text-white text-center h-10}`}
                      
                    >
                      <Button className="w-full h-12 bg-[#171821]" variant={pathname == "/account" ? 'outline' : "ghost"}>
                        <UserOutlined className="mr-2 h-4" />
                        Account
                      </Button>
                    </li>
                  </Link>
                  <Link href="/calculator"> 
                    <li
                      className={`flex items-center justify-center gap-3 border rounded border-none font-bold mb-5 text-white text-center h-10}`}
                      
                    >
                      <Button className="w-full h-12 bg-[#171821]" variant={pathname == "/calculator" ? 'outline' : "ghost"}>
                        <CalculatorOutlined className="mr-2 h-4" />
                        Calculator
                      </Button>
                    </li>
                  </Link>
                  <Link href="/refferal">
                    <li
                     className={`flex items-center justify-center gap-3 border rounded border-none font-bold mb-5 text-white text-center h-10}`}
                      
                    >
                      <Button className="w-full h-12 bg-[#171821]" variant={pathname == "/refferal" ? 'outline' : "ghost"}>
                        <ShareAltOutlined className="mr-2 h-4" />
                        Refferal
                      </Button>
                    </li>
                  </Link>
                </ul>
              </div>
            </div>

            {/* <div className={`${isClicked === true ? "bg-pink" : "bg-transparent"}`}>

            </div> */}

            <div className="col-span-5 lg:col-span-4  p-4 bg-[#171821]">
              <div className="boarder rounded mt-7 mb-5 text-white bg-[#21222d] text-end h-20">
                <button className="bg-blue-500/80 boarder rounded mt-5 mb-5 text-white text-center h-8 mr-4  w-20  ">
                  Connect
                </button>
              </div>

              <div className="h-[2000px] bg-[#171821]">{children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
